#!/usr/bin/perl
# Problem finder for aspectator

$\ = "\n";
$, = "\n";
while (<>){
	chomp;
	/error: invalid storage class for function try_module_get/ and print "<a href =\"http://forge.ispras.ru/issues/380\">bug380:</a> try_module_get";
	/internal compiler error: Segmentation fault/ and print "Segmentation fault";
	/: error: / and print "Compile error";
	/: error: LDV: / and print "LDV error";
	/: warning: / and print "Warning";
	/: warning: LDV: / and print "LDV warning";
	/: fatal error: character .* wasn't put to stream/ and print "<a href=\"http://forge.ispras.ru/issues/349\">Bad_char</a>"
	or /: fatal error: / and print "Fatal_err";
	/tree node '(.*)' isn't supported/ and print "<a href=\"http://forge.ispras.ru/issues/1167\">$1</a>";
	/Aspectator fails on the (.*) stage/ and print "$1 stage";
	/error: redeclaration of '(.*)' with no linkage/ and print "Redeclaration";
}

