#!/usr/bin/perl
# Problem finder for aspectator

$\ = "\n";
$, = "\n";
while (<>){
	chomp;
	/error: invalid storage class for function try_module_get/ and print "<a href =\"http://forge.ispras.ru/issues/380\">bug380:</a> try_module_get";
	/internal compiler error: Segmentation fault/ and print "Segmentation fault";
	/: error: / and print "Compile error";
	/: error: LDV: / and print "LDV error";
	/: warning: / and print "Warning";
	/: warning: LDV: / and print "LDV warning";
	/: fatal error: character .* wasn't put to stream/ and print "<a href=\"http://forge.ispras.ru/issues/349\">Bad_char</a>"
	or /: fatal error: / and print "Fatal_err";
	/tree node '(.*)' isn't supported/ and print "<a href=\"http://forge.ispras.ru/issues/1167\">$1</a>";
	# Old interface to Aspectator (aspectator.sh)
	/Aspectator fails on the (.*) stage/ and print "$1 stage";
	# New interface to Aspectator (cif) 
	/Aspectator failed at '(.*)' stage/ and print "$1 stage";

	/compiler-core: error: kernel.org: No such file or directory/ and print "kernel.org";
	/warning: no return statement in function returning non-void/ and print "No return warn";
	/warning: ISO C90 forbids mixed declarations and code/ and print "Mixed decls warn";
	/error: implicit declaration of function '(.*)'/ and print "Implicit decl";

	#drv-env-gen problems
	/error: storage size of '(.*)' isn't known/ and print "<a href=\"http://forge.ispras.ru/issues/1293\">Storage size</a>";
	/error: implicit declaration of function kmalloc/ and print "DEG: implicit kmalloc";
	/error: redeclaration of '(.*)' with no linkage/ and print "DEG: Redeclaration";
	/error: #endif without #if/ and print "<a href=\"http://forge.ispras.ru/issues/1293\">DEG: ifdefs</a>";
	/error: incompatible types when assigning to type '(.*)' from type '(.*)'/ and print "<a href=\"http://forge.ispras.ru/issues/553\">DEG: return type</a>";

	# misc (see bug #1360)
	/too few arguments to function 'ldv_check_alloc_flags'/ and print "<a href=\"http://forge.ispras.ru/issues/1360\">Few_args</a>";
	/'no_instrument_function' attribute applies only to functions/ and print "<a href=\"http://forge.ispras.ru/issues/1366\">Bad_attr</a>";
	/void value not ignored as it ought to be/ and print "Void_val";
}

