U-spin_lock-__netdev_alloc_page_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-__netdev_alloc_page_nonatomic-spin_unlock.o
S-spin_lock-__netdev_alloc_page_atomic-spin_unlock-test-objs := main.o S-spin_lock-__netdev_alloc_page_atomic-spin_unlock.o

obj-m += U-spin_lock-__netdev_alloc_page_nonatomic-spin_unlock-test.o
obj-m += S-spin_lock-__netdev_alloc_page_atomic-spin_unlock-test.o
