S-tty_flip_buffer_push-test-objs := main.o S-tty_flip_buffer_push.o
U-tty_flip_buffer_push-test-objs := main.o U-tty_flip_buffer_push.o

obj-m += S-tty_flip_buffer_push-test.o
obj-m += U-tty_flip_buffer_push-test.o
