S-nonseek-test-objs := main.o S-nonseek.o
S-nonseek-alone-test-objs := main.o S-nonseek-alone.o
U-nonseek-alone-test-objs := main.o U-nonseek-alone.o

obj-m += S-nonseek-test.o
obj-m += S-nonseek-alone-test.o
obj-m += U-nonseek-alone-test.o

