U-get-put-simple-test-objs := main.o U-get-put-simple.o
U-get-put-simple-2-test-objs := main.o U-get-put-simple-2.o
S-get-put-simple-test-objs := main.o S-get-put-simple.o

obj-m += U-get-put-simple-test.o
obj-m += U-get-put-simple-2-test.o
obj-m += S-get-put-simple-test.o

U-noerrget-put-simple-test-objs := main.o U-noerrget-put-simple.o
U-noerrget-put-simple-2-test-objs := main.o U-noerrget-put-simple-2.o
S-noerrget-put-simple-test-objs := main.o S-noerrget-put-simple.o

obj-m += U-noerrget-put-simple-test.o
obj-m += U-noerrget-put-simple-2-test.o
obj-m += S-noerrget-put-simple-test.o

U-get-putexit-simple-test-objs := main.o U-get-putexit-simple.o
U-get-putexit-simple-2-test-objs := main.o U-get-putexit-simple-2.o
S-get-putexit-simple-test-objs := main.o S-get-putexit-simple.o

obj-m += U-get-putexit-simple-test.o
obj-m += U-get-putexit-simple-2-test.o
obj-m += S-get-putexit-simple-test.o

U-refcounter-simple-2-test-objs := main.o U-refcounter-simple-2.o
U-refcounter-simple-test-objs := main.o U-refcounter-simple.o
S-refcounter-simple-test-objs := main.o S-refcounter-simple.o

obj-m += U-refcounter-simple-2-test.o
obj-m += U-refcounter-simple-test.o
obj-m += S-refcounter-simple-test.o
