S-tty_insert_flip_string-test-objs := main.o S-tty_insert_flip_string.o
U-tty_insert_flip_string-test-objs := main.o U-tty_insert_flip_string.o

obj-m += S-tty_insert_flip_string-test.o
obj-m += U-tty_insert_flip_string-test.o
