#!/usr/bin/perl


# search and replace .ko with .o extension
#
my $module_file = $ARGV[0];
if(!($module_file =~ s/\.ko$/\.o/)) 
{
	if(!($module_file =~ s/\.ko.unsigned$/\.o/)) {
		print "bce_gcc: ERROR: Can't replcae .ko with .o in module_file.\n";
		exit 1;
	}
}

use SOAP::Lite service =>"$ENV{'WSDLADDR'}?wsdl";
marker(SOAP::Data-> type ("string") -> name ("arg0") -> value ($module_file));

