#!/usr/bin/perl -w

################################################################################
# Copyright (C) 2011-2012
# Institute for System Programming, Russian Academy of Sciences (ISPRAS).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

use XML::Twig;
use SOAP::Lite;

my $csd = SOAP::Lite -> service($ENV{'WSDLADDR'}.'?wsdl');

sub xml_cmdstream;

my $twig_handlers = {   "cmdstream/cc"      => \&xml_cmdstream,
                        "cmdstream/ld"      => \&xml_cmdstream };
my $twig_inreport = new XML::Twig(TwigHandlers => $twig_handlers);

$twig_inreport->parsefile($ARGV[0]);
exit;

sub xml_cmdstream {
       	my $cmdstream = XML::Twig::Elt->new('cmdstream');
	$_[1]->move($cmdstream);
	$cmdstream->set_pretty_print('indented');
	$cmdstream->print();
	$csd->sendCommand(SOAP::Data-> type ("string") -> name ("arg0") -> value ($cmdstream->sprint));
}
