#!/bin/sh

#
#
# ldv-task driver workdir=workdir env:rule,rule env:rule,rule ...
#
#
LOG_PREFIX="ldv-task: ";
ldv_print() {
	if [ $LDV_DEBUG -le 0 ]; then if [ -n "`echo $1 | grep WARNING`" -o -n "`echo $1 | grep NORMAL`" -o -n "`echo $1 | grep INFO`" -o -n "`echo $1 | grep DEBUG`" -o -n "`echo $1 | grep TRACE`" -o -n "`echo $1 | grep ALL`" ]; then return; fi;
	elif [ $LDV_DEBUG -le 10 ]; then if [ -n "`echo $1 | grep INFO`" -o -n "`echo $1 | grep DEBUG`" -o -n "`echo $1 | grep TRACE`" -o -n "`echo $1 | grep ALL`" ]; then return; fi;
	elif [ $LDV_DEBUG -le 20 ]; then if [ -n "`echo $1 | grep DEBUG`" -o -n "`echo $1 | grep TRACE`" -o -n "`echo $1 | grep ALL`" ]; then return; fi;
	elif [ $LDV_DEBUG -le 30 ]; then if [ -n "`echo $1 | grep TRACE`" -o -n "`echo $1 | grep ALL`" ]; then return; fi;
	elif [ $LDV_DEBUG -le 40 ]; then if [ -n "`echo $1 | grep ALL`" ]; then return; fi; fi;
	if [ $LDV_DEBUG -ge 40 ]; then 
		echo $LOG_PREFIX"TRACE: Trace mode on. Press any key to cnotinue...";
		read;
	fi;
	echo "$LOG_PREFIX$1";
}
if [ ! -n "$LDV_DEBUG" ]; then LDV_DEBUG=10; fi;


LDV_HOME=`readlink -f \`dirname $0\`/../`;
LDV_DIR=$LDV_HOME/ldv;
LDV_KMANAGER=$LDV_DIR/ldv-kmanager;
LDV_CORE_DIR=$LDV_HOME/ldv-core;
LDV_CORE_EXEC=$LDV_CORE_DIR/ldv-core;

KERNEL_LEVEL=0;

if [ "$1" == "--kernel-driver" ]; then
	KERNEL_LEVEL=1;
else
	DRIVER_ABS=`readlink -f $1`;
	if [ $? -ne 0 ]; then
		ldv_print "ERROR: Can't find abs-path for driver.";
		exit 1;
	fi;
fi;
	
if [ $# -lt 3 ]; then
	ldv_print "ERROR: USAGE: ldv-task driver workdir=wordir env:rule,rule... env:rule,rule... ...";
	exit 1;
fi;


USER_WORKDIR=`echo $2 | sed 's/workdir=//'`
if [ ! -d "$USER_WORKDIR" ]; then
	ldv_print "ERROR: Workdir not exists: \"$WORK_DIR\".";
else
	WORK_DIR=`readlink -f $USER_WORKDIR`;
fi;
ldv_print "INFO: temp workdir: $WORK_DIR";
# all temp dirs created... 
k=1;
tid=1;
for i in $@; do
	if [ $k -eq 1 ]; then
		k=`expr $k + 1`;
		continue;	
	elif [ -n "$USER_WORKDIR" -a $k -eq 2 ]; then 
		k=`expr $k + 1`;
		continue; 
	fi;
	ldv_print "INFO: $i";
	# create dir for this stage
	WORK_DIR_LOCAL=$WORK_DIR/$tid;
	mkdir $WORK_DIR_LOCAL;
	if [ $? -ne 0 ]; then
		ldv_print "ERROR: can not create environment-dir from task: \"$WORK_DIR_LOCAL\".";
		unset WORK_DIR_LOCAL;
		k=`expr $k + 1`;
		tid=`expr $tid + 1`;
		exit 1;
	fi;
	# get KERNELDIR for this environment;
	# kernel-manager return path if kernel-environment exists and correct prepared
	ENV_ID=`echo $i | sed 's/:.*//'`;
	rulemodels=`echo $i | sed 's/.*://'`;
	ldv_print "DEBUG: rulemodels: $rulemodels";
	if [ ! -n "$rulemodels" ]; then
		ldv_print "ERROR: rulemodels after \":\" is null. Please, setup it.";
		unset ENV_ID;
		unset KERNEL_PATH;
		unset WORK_DIR_LOCAL;
		k=`expr $k + 1`;
		tid=`expr $tid + 1`;
		exit 1;
	fi;
	ldv_print "INFO: env_id: $ENV_ID";
	ldv_print "INFO: workdir: $WORK_DIR_LOCAL";
	KERNEL_PATH=`$LDV_KMANAGER getpath $ENV_ID`;
	if [ $? -ne 0 ]; then
		ldv_print "ERROR: ldv-kmanager return error for this environment: \"$KERNEL_PATH\".";
		unset ENV_ID;
		unset KERNEL_PATH;
		unset WORK_DIR_LOCAL;
		k=`expr $k + 1`;
		tid=`expr $tid + 1`;
		exit 1;
	fi;
	ldv_print "NORMAL: Calling LDV-core.";
	if [ $KERNEL_LEVEL -eq 0 ]; then
		ldv_print "DEBUG: WORK_DIR=$WORK_DIR_LOCAL $LDV_CORE_EXEC --env=$KERNEL_PATH --driver=$DRIVER_ABS --rule-models=$rulemodels;";
		WORK_DIR=$WORK_DIR_LOCAL $LDV_CORE_EXEC --env=$KERNEL_PATH --driver=$DRIVER_ABS --rule-models=$rulemodels;
	else
		ldv_print "DEBUG: WORK_DIR=$WORK_DIR_LOCAL $LDV_CORE_EXEC --env=$KERNEL_PATH --driver-kernel --rule-models=$rulemodels;";
		WORK_DIR=$WORK_DIR_LOCAL $LDV_CORE_EXEC --env=$KERNEL_PATH --driver-kernel --rule-models=$rulemodels;
	fi;

	if [ $? -ne 0 ]; then
		ldv_print "ERROR: ldv-core failed.";
	fi;
	unset ENV_ID;
	unset KERNEL_PATH;
	unset WORK_DIR_LOCAL;
	k=`expr $k + 1`;
	tid=`expr $tid + 1`;
done;




