#!/usr/bin/perl -w
#

use XML::Twig;
use FindBin;
use File::Find;

my $deg_home = "$FindBin::Bin";

# Xml nodes names.
my $xml_cmd_basedir = 'basedir';
my $xml_cmd_stream = 'cmdstream';
my $xml_cmd_attr_id = 'id';
my $xml_cmd_attr_check = 'check';
my $xml_cmd_entry_point = 'main';
my $xml_cmd_cc = 'cc';
my $xml_cmd_cwd = 'cwd';
my $xml_cmd_in = 'in';
my $xml_cmd_ld = 'ld';
my $xml_cmd_opt = 'opt';
my $xml_cmd_out = 'out';
my $xml_reports_cc = 'cc';
my $xml_reports_ld = 'ld';
my $xml_reports_attr_ref = 'ref';
my $xml_reports_att_env = 'kernel';
my $xml_reports_verdict = 'verdict';
my $xml_reports = 'reports';
my $xml_reports_build = 'build';

my $verdict_unknown = 'UNKNOWN';
my $verdict_ok = 'OK';

my $xml_instrument = 'ldv';
my $xml_instrument_status = 'status';
my $xml_instrument_time = 'time';
my $xml_instrument_desc = 'desc';

#####################################################
# log options
#####################################################
my $psuffix="ldv-task-reporter";
my $log_level=10;

my $cmdfile = "";
my $report_out = "";
my $report_name = "";
my $reports_dir = "";
my $state_file = "";
my @reports;

# 0. get options.
get_ldv_opts();
# 1. read state file;
open(FIL,$state_file); 
my @states = <FIL>; 
close(FIL);

# 0.1 read all report files ant cut its to one temp report file
my $twig_inreport = XML::Twig->new();
$twig_inreport->set_xml_version( '1.0');
my $twig_inroot = XML::Twig::Elt->new($xml_reports);
$twig_inreport->set_root($twig_inroot);

# 0.2 get all reports files
@reports=get_reports();
foreach my $file (@reports) { 
	ldv_dprint("Grep file: \"$file\".");
	my $ctwig=new XML::Twig();
	$ctwig->parsefile($file);
	my $croot=$ctwig->root;
	my @childrens = $croot->children();
	foreach my $section (@childrens) {
		if ($section->name eq $xml_reports_cc || $section->name eq $xml_reports_ld || $section->name eq $xml_reports_build) {
			hxml_cmdstream($section,$file);
		}
		$section->move($twig_inroot);
	}
};

$twig_inreport->set_pretty_print('indented');
$twig_inreport->print_to_file($report_out);
ldv_dprint("Report created successfully.");


#####################################################
# xml-functions
#####################################################
sub search {  push (@filelist,$File::Find::name) if(!-d); }
sub get_reports {
	my @local_reports=();
	find(\&search, $reports_dir);
	my @out_reports=();
	foreach(@filelist) { if(/.*$report_name/) { push(@out_reports,$_); } }
	return @out_reports;
}
#####################################################
# twig  handlers
#####################################################

sub hxml_cmdstream {
	my @state=get_state($_[1]);
	$_[0]->set_att($xml_reports_att_env=>$state[0]);
}	

sub get_state {
	foreach my $lstate (@states) {
		if($lstate =~ m/^(.*):(.*)$/) {
			my $path=$2;
			my $envid=$1;
			if($_[0] =~ m/$path/) {
				my @state=($envid,"0");	
				return @state;
			}	
		}
	}
}

######################################################
# option test
######################################################
sub get_ldv_opts
{
	$log_level = $ENV{'LDV_DEBUG'};

	# get all options
	foreach $opt(@ARGV)
	{
		if($opt =~ s/--reports-dir=(.*)/$1/)
		{
			$reports_dir = $opt;
		}
		elsif($opt =~ s/--report-name=(.*)/$1/)
		{
			$report_name = $opt;
		}
		elsif($opt =~ s/--state-file=(.*)/$1/)
		{
			$state_file = $opt;
		}
		elsif($opt =~ s/--report-out=(.*)/$1/)
		{
			$report_out = $opt;
		}
		else
		{
			ldv_eprint("Unknown option:\"$opt\".");
			exit 1;
		}
	}
	# test all options
	if(!$report_name) {
		ldv_eprint("You must setup input report filename: \"--report-name\".");
		print_usage();
		exit 1;
	}
	if(!$state_file) {
		ldv_eprint("You must setup file with state: \"--state-file\".");
		print_usage();
		exit 1;
	} elsif(! -f $state_file) {
		ldv_eprint("Can not find file with state: \"$state_file\".");
		print_usage();
		exit 1;
	}
	if(!$reports_dir) {
		ldv_eprint("You must setup output reports dir in option: \"--reoports-dir\".");
		print_usage();
		exit 1;
	} elsif(! -d $reports_dir) {
		ldv_eprint("Directory with reports not exists: \"$reports_dir\".");
		print_usage();
		exit 1;
	} 
	if(!$report_out) {
		ldv_eprint("You must setup output report file in option: \"--reoport-out\".");
		print_usage();
		exit 1;
	} elsif( -f $report_out) {
		ldv_eprint("Output report file already exists: \"$report_out\".");
		print_usage();
		exit 1;
	}
}

sub print_usage
{
	ldv_print("USAGE: $psuffix --reports-dir=reportsdir --report-out=reportfile --report-name=reportname --state-file=statefile");
}

#######################################################
# ldv print functions
#######################################################
sub ldv_print
{
	print "$psuffix: $_[0]\n";
}

sub ldv_eprint
{
	ldv_print "ERROR: $_[0]";
}

sub ldv_sprint
{
	if($log_level>=10) {
		ldv_print("$_[0]");
	}
}

sub ldv_iprint
{
	if($log_level>=20) {
		ldv_print("INFO: $_[0]");
	}
}

sub ldv_dprint
{
	if($log_level>=30) {
		ldv_print("DEBUG: $_[0]");
	}
}

sub ldv_tprint
{
	if($log_level>=40) {
		ldv_print("TRACE: $_[0]");
	}
}

sub ldv_aprint
{
	if($log_level==100) {
		ldv_print("$_[0]");
	}
}
