S-tty_encode_baud_rate-test-objs := main.o S-tty_encode_baud_rate.o
U-tty_encode_baud_rate-test-objs := main.o U-tty_encode_baud_rate.o

obj-m += S-tty_encode_baud_rate-test.o
obj-m += U-tty_encode_baud_rate-test.o
