#!/bin/bash

bindir = $(prefix)/bin
scripts = scripts

# Phony targets.
.PHONY: all install test clean

# Default make action.
all:
	@echo The Public Pool of Bugs \(re\)generator doesn\'t require compilation

# Install needed executables to specified path.
install:
	mkdir -p $(bindir)
	cp ${scripts}/* $(bindir)

test:
	@echo The Public Pool of Bugs \(re\)generator doesn\'t have any test

clean:
	@echo The Public Pool of Bugs \(re\)generator doesn\'t require cleaning 
