S-tty_buffer_request_room-test-objs := main.o S-tty_buffer_request_room.o
U-tty_buffer_request_room-test-objs := main.o U-tty_buffer_request_room.o

obj-m += S-tty_buffer_request_room-test.o
obj-m += U-tty_buffer_request_room-test.o
