#!/usr/bin/env ruby
#
# Watch for tasks to be completed in order
#

require 'fileutils'
require 'find'
require 'logger'

# Set path to gems so that our gems are automatically loaded
ENV['GEM_PATH'] = File.join(File.dirname(__FILE__),"..","shared","ruby","gem") + (ENV['GEM_PATH']?":#{ENV['GEM_PATH']}":"") + ":" + (`gem env gempath`.chomp)
# Require gems
require 'rubygems'
$:.unshift File.dirname(__FILE__)
require 'generic.rb'
$:.unshift File.join(File.dirname(__FILE__),"..","shared","ruby","lib")
require 'ldv_logging'

# Set up logging
$log = LDV::Logging::generic 'watcher'

# Process command arguments
#
# FIXME: for now this sample watcher only supports parallelization of RCV commands

address = ENV['LDV_WATCHER_SRV'] or raise "Server address not found.  Please, specify LDV_WATCHER_SRV env var!"

def address_local? addr
	addr =~ /^\//
end

watcher = nil
if address_local? address
	command = ARGV.shift
	arguments = ARGV
	require 'local.rb'
	watcher = WatcherLocal.new(address)
else
	$:.unshift File.join(File.dirname(__FILE__),"..","cluster")
	require 'cluster-watcher.rb'
	require 'options.rb'

	opts_p = ClusterOptionsParser.new({})
	opts_p.do_parse

	command = ARGV.shift
	arguments = ARGV

	# Comment out due to lack of proper logging here
	#$stderr.puts "New watcher: #{({:host => address}.merge opts_p.options).inspect}"
	watcher = WatcherRemote.new({:host => address}.merge opts_p.options)
end

# Log command to a special file
# NOTE: thread-unsafe!  Too lazy to fix though
if ENV['LDV_TEST_WAITER_FNAME']
	cmd_args = [command] + arguments
	# Quick hack: we just replace commas with dots, it's not the best solution...
	File.open(ENV['LDV_TEST_WAITER_FNAME'],"a") {|f| f.puts "#{(ENV['LDV_SPAWN_KEY']||"<none>").gsub(/,/,'.')}: #{cmd_args.join(" ")}" }
else
	## comment out due to lack of proper logging here
	#$stderr.puts "#{ENV['LDV_SPAWN_KEY']}: #{([command]+arguments).join(" ")}"
end

# Log command to a special file
# NOTE: thread-unsafe!  Too lazy to fix though
if ENV['LDV_TEST_WAITER_FNAME']
	cmd_args = [command] + arguments
	ENV['LDV_SPAWN_KEY'] ||= ''
	# Quick hack: we just replace commas with dots, it's not the best solution...
	File.open(ENV['LDV_TEST_WAITER_FNAME'],"a") {|f| f.puts "#{ENV['LDV_SPAWN_KEY'].gsub(/,/,'.')}: #{cmd_args.join(" ")}" }
else
	$log.trace "#{ENV['LDV_SPAWN_KEY']}: #{([command]+arguments).join(" ")}"
end

result = nil
unless arguments.empty?
	result = watcher.send command, *arguments
else
	result = watcher.send command
end

puts result unless result.nil?

$log.close

