#!/usr/bin/env ruby
#
# Watch for tasks to be completed in order
#

require 'fileutils'
require 'find'
require 'logger'

require 'rubygems'
$:.unshift File.dirname(__FILE__)
require 'generic.rb'

# Set up logging
$log = Logger.new(STDERR)
# NOTE: for compatibility we use different levels
levels = { 0 => Logger::FATAL, 4 => Logger::ERROR, 10 => Logger::WARN, 20 => Logger::INFO, 30 => Logger::DEBUG }
user_set_level = (ENV['LDV_DEBUG'] || '10').to_i;
$log.level = levels[levels.keys.select{|l| l <= user_set_level}.max]

# Process command arguments
#
# FIXME: for now this sample watcher only supports parallelization of RCV commands

address = ENV['LDV_WATCHER_SRV'] or raise "Server address not found.  Please, specify LDV_WATCHER_SRV env var!"

def address_local? addr
	addr =~ /^\//
end

watcher = nil
if address_local? address
	command = ARGV.shift
	arguments = ARGV
	require 'local.rb'
	watcher = WatcherLocal.new(address)
else
	require 'cluster.rb'
	$:.unshift File.join(File.dirname(__FILE__),"..","cluster")
	require 'options.rb'

	opts_p = ClusterOptionsParser.new({})
	opts_p.do_parse

	command = ARGV.shift
	arguments = ARGV

	watcher = WatcherRemote.new({:host => address}.merge opts_p.options)
end

result = nil
unless arguments.empty?
	result = watcher.send command, *arguments
else
	result = watcher.send command
end

puts result unless result.nil?

$log.close

