# Standard directory for installation of main LDV executables.
bindir = $(prefix)/bin

.PHONY: all install test clean

all:
	#@echo "Resource Manager doesn't require build itself"

install:
	@mkdir -p $(bindir)
	#cp res-manager $(bindir)

test:
	#@echo "Resource Manager hasn't tests at the moment"

clean:
	#@echo "Resource Manager hasn't build files"
