<!--<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>

    <h3>This is your project's main page</h3>

    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>-->
<h1>Statistics server user guide.</h1>
<h3>1st step. Establish your session database connection.</h3>
<p>To do this follow link '<a href="<?php echo $this->url(
            array('controller'=>'stats', 'action'=>'signdb'),
            'default',
            true) ?>"><b>Sign database connection</b></a>' at the right-up page corner. You may always do this operation on any shown page.</p>
<p>The default statistics server layout will be shown if you will skip this step and every time when you begin a new session.</p>
<h3>2d step. Show summary statistics.</h3>
<p>To do this follow link '<a href="<?php echo $this->url(
            array('controller'=>'stats', 'action'=>'index'),
            'default',
            true) ?>"><b>Show statistics</b></a>' at the right-up page corner. You may always do this operation on any shown page.</p>
<p>The page where you'll be redirected contains summarized statistics on all launches grouped and sorted by the default way.</p>
<p>There you may do following actions:
<ul>
  <li>Click on the corresponding instruments failures links to see their detailed description.</li>
  <li>Click on the RCV OK links to see detailed description of unsafe situations with related raw error traces.</li>
</ul>
<br><br> 
<h3>You may go to the index page (i.e. this page).</h3>
<p>To do this follow link '<a href="<?php echo $this->url(
            array('controller'=>'index', 'action'=>'index'),
            'default',
            true) ?>"><b>Index</b></a>' at the right-up page corner. You may always do this operation on any shown page.</p>
<h3>You may ask questions and make feedback.</h3>
<p>To do this write e-mail '<a href="mailto:joker@ispras.ru"><b>Support</b></a>' at the right-up page corner. You may always do this operation on any shown page.</p>
<br><br> 
<h3>Server statistics change log.</h3>
<h3>1.3</h3>
<ul>
  <li>Add global style by means of css.</li>
  <li>Error trace is visualized a bit now.</li>
</ul>
<h3>1.2</h3>
<ul>
  <li>This change log is arised.</li>
  <li>Showing of build errors is fixed.</li>
</ul>
<h3>1.1</h3>
<ul>
  <li>The statistics server version (the number at the top and page title).</li>
  <li>Division on safe/unsafe for the RCV.</li>
  <li>Fail descriptions are printed without any formatting (&lt;pre&gt; tag is used for this).</li>
</ul>
<h3>1.0</h3>
<ul>
  <li>The initial release.</li>
</ul>
