S-tty_standard_install-test-objs := main.o S-tty_standard_install.o
U-tty_standard_install-test-objs := main.o U-tty_standard_install.o

obj-m += S-tty_standard_install-test.o
obj-m += U-tty_standard_install-test.o
