#!/bin/bash

#
# env var WORK_DIR
# ldv-core --env=envdir --driver=driver --rule-models=rules
#

XML_FILENAME_AFTER_BCE="cmd_after_bce.xml";
XML_FILENAME_AFTER_CSD="cmd_after_csd";
XML_FILENAME_AFTER_DEG="cmd_after_deg.xml";

DEG_STATE_FILENAME="deg.state";
CSD_STATE_FILENAME="csd.state";

DEG_REPORT_FILENAME="report_after_deg.xml";
CSD_REPORT_FILENAME="report_after_csd.xml";
BCE_REPORT_FILENAME="report_after_bce.xml";
DSCV_REPORT_FILENAME="report_after_dscv.xml";

DSCV_TEMPDIR_NAME="dscv_tempdir";
CSD_TEMPDIR_NAME="csd_tempdir";
DEG_TEMPDIR_NAME="deg_tempdir";
BCE_TEMPDIR_NAME="bce_tempdir";
CSD_DEG_DSCV_TEMPDIR_NAME="csd_deg_dscv";

LOG_MIRROR_TO_CONSOLE=1;
DRIVER_DIR_NAME="driver";
EXTRACTOR_LOG_FILENAME="unarch.log";


LDV_HOME=`readlink -f \`dirname $0\`/../`;
LOG_PREFIX="ldv-core: ";
USAGE_STRING="WORK_DIR=workdir ldv-core --env=kerneldir --driver=driverpath --rule-models=rulemodels";
source $LDV_HOME/shared/sh/log.sh;

BCE_DIRNAME="build-cmd-extractor";
BCE_DIR=$LDV_HOME/$BCE_DIRNAME;
CSD="java -ea -jar $BCE_DIR/csd.jar";
CSD_REPORTER="$BCE_DIR/cmd-stream-divider-reporter";

LDV_TEMPDIR_NAME="ldv_tempdir";

LDV_RULE_DB_DIRNAME="kernel-rules";
LDV_RULE_DB=$LDV_HOME/$LDV_RULE_DB_DIRNAME;

LDVC_DIR="$LDV_HOME/ldv-core";
LDVC_REPORTER="$LDVC_DIR/ldv-core-reporter";

BCE_DIR="$LDV_HOME/build-cmd-extractor";
BCE="$BCE_DIR/build-cmd-extractor";
BCE_REPORTER="$BCE_DIR/build-cmd-extractor-reporter";

STATS="$LDV_HOME/shared/sh/timeout";
STATS_LOG_FILENAME="stats.xml";

DEG_DIR="$LDV_HOME/drv-env-gen";
DEG="$DEG_DIR/drv-env-gen";
DEG_REPORTER="$DEG_DIR/drv-env-gen-reporter";

DSCV_DIR="$LDV_HOME/bin/";
DSCV="$DSCV_DIR/dscv";

RINSTR_DIR="$LDV_HOME/rule-instrumentor";
RINSTR="$RINSTR_DIR/rule-instrumentor.pl";

KERNEL_LEVEL=0;

bce_create_report() {
	BCE_REPORT=$BCE_TEMPDIR/$BCE_REPORT_FILENAME;
	if [ -n "$1" ]; then
		echo "<?xml version=\"1.0\"?>" > $BCE_REPORT;
		echo "<reports>" >> $BCE_REPORT;
		echo "  <build>" >> $BCE_REPORT;
		echo "    <status>$1</status>" >> $BCE_REPORT;
		echo "    <time></time>" >> $BCE_REPORT;
		if [ -f "$BCE_STATE" ]; then
			BCE_ERR_DESCRIPTION=`cat $BCE_STATE`;
		else
			BCE_ERR_DESCRIPTION=$2;
		fi;
		echo "    <desc>$BCE_ERR_DESCRIPTION</desc>" >> $BCE_REPORT;
		echo "  </build>" >> $BCE_REPORT;
		echo "</reports>" >> $BCE_REPORT;
	else
		ldv_print "NORMAL: Calling Build Commmand Extractor Reporter.";
		ldv_print "DEBUG: $BCE_REPORTER --stats-file=$BCE_STATS_LOG --report-in=$CSD_REPORT --report-out=$BCE_REPORT --state-file=$BCE_STATE;";
		$BCE_REPORTER --stats-file=$BCE_STATS_LOG --report-in=$CSD_REPORT --report-out=$BCE_REPORT --state-file=$BCE_STATE;
		if [ $? -ne 0 ]; then
		        ldv_print "ERROR: BCE reporter failed.";
		        exit 1;
		fi;
	fi;
};

ldv_create_report() {
	ldv_print "NORMAL: Calling LDV-Core Reporter.";
	ldv_print "DEBUG: $LDVC_REPORTER --report-in=$BCE_REPORT --report-out=$reportout --state-dir=$TEMP_DIR;";
	$LDVC_REPORTER --report-in=$BCE_REPORT --report-out=$reportout --state-dir=$TEMP_DIR;
	if [ $? -ne 0 ]; then
	        ldv_print "ERROR: LDV-Core reporter failed.";
	        exit 1;
	fi;
};

deg_create_report() {
 	DEG_REPORT=$DEG_TEMPDIR/$DEG_REPORT_FILENAME;
	ldv_print "NORMAL: Calling Driver Environment Generator reporter.";
	ldv_print "DEBUG: $DEG_REPORTER --stats-file=$DEG_STATS --cmdfile=$xml_after_csd --report-in=$DSCV_REPORT --report-out=$DEG_REPORT --state-file=$DEG_STATE;";
	$DEG_REPORTER --stats-file=$DEG_STATS --cmdfile=$xml_after_csd --report-in=$DSCV_REPORT --report-out=$DEG_REPORT --state-file=$DEG_STATE;
	if [ $? -ne 0 ]; then 
		ldv_print "ERROR: DEG reporter failed."; 
		
	fi;
};

bce_ldv_report() {
	#
	# add build command extractor reports
	#
	bce_create_report "$1" "$2";
	#
	# add ldv-core reports
	#
	ldv_create_report;
};


if [ ! -n "$WORK_DIR" ]; then
	ldv_print "ERROR: Please, setup WORK_DIR variable before running ldv-core.";
	exit 1;
fi;
WORK_DIR=`readlink -f $WORK_DIR`;
if [ $? -ne 0 ]; then
        ldv_print "ERROR: Failed to read abs-path for working dir: \"$WORK_DIR\"."
        exit 1;
fi;
if [ ! -d "$WORK_DIR" ]; then
        ldv_print "ERROR: Working directory does not exists: \"$WORK_DIR\".";
        exit 1;
fi;

#
# scan and test command line parameters
#
for arg in $@; do
        case $arg in
                --rule-models=*)
                	rulemodels=`echo $arg | sed 's/--rule-models=//g'`
			if [ ! -n "$rulemodels" ]; then
				ldv_print "ERROR: Parameter \"--rule-models\" - is null. Setup it.";
			        exit 1;
			fi;
                ;;
		--report-out=*)
                	rreportout=`echo $arg | sed 's/--report-out=//g'`
			if [ ! -n "$rreportout" ]; then
				ldv_print "ERROR: Parameter \"--report-out\" - is null. Setup it.";
			        exit 1;
			fi;
			reportout=`readlink -f $rreportout`;
			if [ $? -ne 0 ]; then
				ldv_print "ERROR: Failed to read abs-path for out report file: \"$rreportout\"."
			        exit 1;
			fi;
			if [ -d "$reportout" ]; then
			        ldv_print "ERROR: Report file already exists as dir: \"$reportout\".";
			        exit 1;
			fi;
			if [ -f "$reportout" ]; then
			        ldv_print "ERROR: Out report file already exists: \"$reportout\".";
			        exit 1;
			fi;
               	;;
		--env=*)
                	renv=`echo $arg | sed 's/--env=//g'`
			if [ ! -n "$renv" ]; then
				ldv_print "ERROR: Parameter \"--env\" - is null. Setup it.";
			        exit 1;
			fi;
			env=`readlink -f $renv`;
			if [ $? -ne 0 ]; then
				ldv_print "ERROR: Failed to read abs-path for environment dir: \"$renv\"."
			        exit 1;
			fi;
			if [ ! -d "$env" ]; then
			        ldv_print "ERROR: Environment dir not exists: \"$env\".";
			        exit 1;
			fi;
                ;;
                --cmdstream=*)
                        rcmdstream=`echo $arg | sed 's/--cmdstream=//g'`
                        if [ ! -n "$rcmdstream" ]; then
                                ldv_print "ERROR: Parameter \"--cmdstream\" - is null. Setup it.";
                                exit 1;
                        fi;
                ;;
                --kernel-driver)
 			KERNEL_LEVEL=1;	
		;;
                --driver=*)
                	rdriver=`echo $arg | sed 's/--driver=//g'`
			if [ ! -n "$rdriver" ]; then
				ldv_print "ERROR: Parameter \"--driver\" - is null. Setup it.";
			        exit 1;
			fi;
                ;;
                *)
                        ldv_print "ERROR: Unknown options: '$arg'.";
			print_usage_and_exit;
                ;;
        esac
done

if [ -n "$rcmdstream" ]; then
	ldv_print "INFO: Artificial cmdstream mode.";
        cmdstream=`echo "readlink -f $rcmdstream" | sh`;
        if [ $? -ne 0 ]; then
                ldv_print "ERROR: Failed to read abs-path for cmdstream file: \"$cmdstream\"."
                exit 1;
        fi;
        if [ ! -f "$cmdstream" ]; then
                ldv_print "ERROR: Cmdstream file not exists: \"$cmdstream\".";
                exit 1;
        fi;
else
	if [ $KERNEL_LEVEL -eq 0 ]; then
		driver=`readlink -f $rdriver`;
		if [ $? -ne 0 ]; then
			ldv_print "ERROR: Failed to read abs-path for driver source: \"$rdriver\"."
		        exit 1;
		fi;
		if [ ! -f "$driver" ]; then
		        ldv_print "ERROR: Driver sources not exists: \"$driver\".";
		        exit 1;
		fi;
	else 
		driver=$rdriver;
		if [ $? -ne 0 ]; then
			ldv_print "ERROR: Can't get abs path for driver in kernel.";
			exit 1;
		fi;
	fi;
	if [ ! -n $reportout ]; then
		ldv_print "ERROR: Please setup out report file option: \"--report-out\".";
	fi;
	if [ ! -n $driver ]; then
		ldv_print "ERROR: Please setup driver in option: \"--driver\".";
	fi;
fi;

if [ ! -n $env ]; then
	ldv_print "ERROR: Please setup environment in option: \"--env\".";
fi;

if [ ! -n $rulemodels ]; then
	ldv_print "ERROR: Please setup rules and models in option: \"--rulemodels\".";
fi;

BCE_TEMPDIR=$WORK_DIR/$BCE_TEMPDIR_NAME;
mkdir $BCE_TEMPDIR;
if [ $? -ne 0 ]; then
	ldv_print "ERROR: Can't create build-cmd-extractor dir: \"$BCE_TEMPDIR\"";
	exit 1;
fi;

TEMP_DIR=$WORK_DIR/$LDV_TEMPDIR_NAME;
mkdir $TEMP_DIR;
if [ $? -ne 0 ]; then
        ldv_print "ERROR: Failed to create next working dir for bce: \"$TEMP_DIR\"."
        exit 1;
fi;

UNARCH_LOG=$TEMP_DIR/$EXTRACTOR_LOG_FILENAME;
touch $UNARCH_LOG;
if [ $? -ne 0 ]; then
	ldv_print "ERROR: Failed to create log for unarchiver: \"$UNARCH_LOG\".";
	exit 1;
fi;

if [ ! -n "$cmdstream" ]; then
	DRIVER_DIR=$TEMP_DIR/$DRIVER_DIR_NAME;
	if [ $KERNEL_LEVEL -eq 0 ]; then
		ldv_print "NORMAL: Prepare driver."
		mkdir $DRIVER_DIR;
		if [ $? -ne 0 ]; then
		        ldv_print "ERROR: Failed to create driver dir for next instrument:\"$DRIVER_DIR\"."
		        exit 1;
		fi;
		#
		# test format for driver file and unpack driver
		#
		case `file -b $driver --mime-type` in
			application/x-bzip2)
				tar xvjpf $driver -C $DRIVER_DIR > $UNARCH_LOG 2>&1;; 
			application/x-gzip)
				tar xvzpf $driver -C $DRIVER_DIR > $UNARCH_LOG 2>&1;; 
			*)
				bce_ldv_report "FAILED" "Driver source type not supported.";
				ldv_print "ERROR: Unknown driver source type.";
				exit 0;;
		esac
		if [ $? -ne 0 ]; then
			bce_ldv_report "FAILED" "Failed to unpack driver source.";
		        ldv_print "ERROR: Failed to unpacked archive: \"$driver\".";
	       		exit 0;
		fi;
	else
		ldv_print "NORMAL: Copy in-kernel driver environment."
		ldv_print "DEBUG: cp -r $env $DRIVER_DIR;"
		cp -r $env $DRIVER_DIR;
		env=$DRIVER_DIR;
		DRIVER_DIR=$driver;
		if [ $? -ne 0 ]; then
			ldv_print "ERROR: Can't copy drivers source code.";
			exit 1;
		fi;
	fi;
fi;

BCE_TEMPDIR=$WORK_DIR/$BCE_TEMPDIR_NAME;
BCE_STATE=$BCE_TEMPDIR/"err.state";



ldv_print "NORMAL: Calling Build Command Extractor";
if [ -n "$cmdstream" ]; then
	XML_AFTER_BCE=$cmdstream;
	stream_option="--cmdstream=$cmdstream";
	koption=--kernel-driver;
else
	XML_AFTER_BCE=$BCE_TEMPDIR/$XML_FILENAME_AFTER_BCE;
	if [ $KERNEL_LEVEL -eq 1 ]; then koption=--kernel-driver; fi;
	stream_option="--driver=$DRIVER_DIR";
fi;

BCE_STATS_LOG="$BCE_TEMPDIR/$STATS_LOG_FILENAME";
touch $BCE_STATS_LOG;
if [ $? -ne 0 ]; then
	ldv_print "ERROR: Can't touch stats file:\"$BCE_STATS_LOG\".";
	exit 1;
fi;
ldv_print "DEBUG: LDV_DEBUG=$LDV_DEBUG WORK_DIR=$WORK_DIR $STATS -p .*,ALL\;.*bce_gcc.*,BCE_GCC\;.*as_gcc.*,AS_GCC\;.*cc1.*,CC1 -o $BCE_STATS_LOG $BCE --env=$env --basedir=$BCE_TEMPDIR_NAME --state=$BCE_STATE --cmdfile-out=$XML_AFTER_BCE $koption $stream_option;"
                  LDV_DEBUG=$LDV_DEBUG WORK_DIR=$WORK_DIR $STATS -p .*,ALL\;.*bce_gcc.*,BCE_GCC\;.*as_gcc.*,AS_GCC\;.*cc1.*,CC1 -o $BCE_STATS_LOG $BCE --env=$env --basedir=$BCE_TEMPDIR_NAME --state=$BCE_STATE --cmdfile-out=$XML_AFTER_BCE $koption $stream_option;

#if [ -n "$cmdstream" ]; then
#	XML_AFTER_BCE=$cmdstream;
#	ldv_print "DEBUG: LDV_DEBUG=$LDV_DEBUG WORK_DIR=$WORK_DIR $BCE --cmdstream=$cmdstream --basedir=$BCE_TEMPDIR_NAME --state=$BCE_STATE --cmdfile-out=$XML_AFTER_BCE;"
#	LDV_DEBUG=$LDV_DEBUG WORK_DIR=$WORK_DIR $BCE --cmdstream=$cmdstream --basedir=$BCE_TEMPDIR_NAME --state=$BCE_STATE --cmdfile-out=$XML_AFTER_BCE;
#else 
#	XML_AFTER_BCE=$BCE_TEMPDIR/$XML_FILENAME_AFTER_BCE;
#	if [ $KERNEL_LEVEL -eq 1 ]; then koption=--kernel-driver; fi;
#	ldv_print "DEBUG: LDV_DEBUG=$LDV_DEBUG WORK_DIR=$WORK_DIR $BCE --env=$env             --basedir=$BCE_TEMPDIR_NAME --state=$BCE_STATE --driver=$DRIVER_DIR --cmdfile-out=$XML_AFTER_BCE $koption;"
#	LDV_DEBUG=$LDV_DEBUG WORK_DIR=$WORK_DIR $BCE --env=$env --basedir=$BCE_TEMPDIR_NAME --state=$BCE_STATE --driver=$DRIVER_DIR --cmdfile-out=$XML_AFTER_BCE $koption;
#fi;
if [ $? -ne 0 ]; then
	ldv_print "ERROR: Cmd extractor failed.";
	bce_ldv_report "FAILED" "Build command extractor failed.";
	exit 0;
fi;
#
# FAST FIX : remove LD commands that contains <in> sections 
#            without corresponding CC commands !!!
#
$LDV_HOME/ldv-core/fast_fix_cmdstream.pl $XML_AFTER_BCE;
if [ $? -ne 0 ]; then
	ldv_print "ERROR: Fast fix failed.";
	bce_ldv_report "FAILED" "Fast fix for cmdstream failed.";
	exit 0;
fi;

#
# Try to call CSD:
#   CSD_TEMPDIR_NAME - directory in WORK_DIR where contains:
#     files XML_FILENAME_AFTER_CSD[index].xml
#
ldv_print "NORMAL: Calling Command Stream Divider.";
#ldv_print "DEBUG:                                                                  ";
#ldv_print "DEBUG:  Option \"--print-digraph\" shown graph for graphviz tool.       ";
#ldv_print "DEBUG:  You can see this graph in graphical mode:                       ";
#ldv_print "DEBUG:     - copy to FILE all in \"diraph G{...}\".                     ";
#ldv_print "DEBUG:     - call: dot -Tpng ./FILE -o ./FILE.png & gwenview ./FILE.png ";
#ldv_print "DEBUG:                                                                  ";

CSD_TEMPDIR=$WORK_DIR/$CSD_DEG_DSCV_TEMPDIR_NAME;
CSD_STATE=$CSD_TEMPDIR/$CSD_STATE_FILENAME;
if [ $KERNEL_LEVEL -eq 1 ]; then
	ldv_print "DEBUG: LDV_DEBUG=$LDV_DEBUG WORK_DIR=$WORK_DIR $CSD --split-on --print-digraph --cmdfile=$XML_AFTER_BCE --basedir=$CSD_DEG_DSCV_TEMPDIR_NAME --cmdfile-out=$XML_FILENAME_AFTER_CSD --state-file=$CSD_STATE;";
	LDV_DEBUG=$LDV_DEBUG WORK_DIR=$WORK_DIR $CSD --split-on $PRINT_DIGRAPH_OPTION --cmdfile=$XML_AFTER_BCE --basedir=$CSD_DEG_DSCV_TEMPDIR_NAME --cmdfile-out=$XML_FILENAME_AFTER_CSD --state-file=$CSD_STATE;
else
	ldv_print "DEBUG: LDV_DEBUG=$LDV_DEBUG WORK_DIR=$WORK_DIR $CSD --full-copy --split-on --print-digraph --cmdfile=$XML_AFTER_BCE --basedir=$CSD_DEG_DSCV_TEMPDIR_NAME --cmdfile-out=$XML_FILENAME_AFTER_CSD --state-file=$CSD_STATE;";
	LDV_DEBUG=$LDV_DEBUG WORK_DIR=$WORK_DIR $CSD --full-copy --split-on $PRINT_DIGRAPH_OPTION --cmdfile=$XML_AFTER_BCE --basedir=$CSD_DEG_DSCV_TEMPDIR_NAME --cmdfile-out=$XML_FILENAME_AFTER_CSD --state-file=$CSD_STATE;
fi;
if [ $? -ne 0 ]; then
       ldv_print "ERROR: Command stream divider failed.";
       exit 1;
fi;
CSD_DEG_DSCV_TEMPDIR=$WORK_DIR/$CSD_DEG_DSCV_TEMPDIR_NAME;
if [ ! -d $CSD_DEG_DSCV_TEMPDIR ]; then
       ldv_print "ERROR: Can't find command stream divider temp directory:\"$CSD_DEG_DSCV_TEMPDIR_NAME\".";
       exit 1;
fi;

# 
# Find all xml files in csd_tempdir and try to call all other instruments
#
for xml_after_csd in `find $CSD_DEG_DSCV_TEMPDIR -maxdepth 1 -regex ".*$XML_FILENAME_AFTER_CSD[0-9]+\.xml$" -type f`; do
	LAST_DRIVER_DIR=`cat $xml_after_csd | grep '<basedir>' | sed 's/<basedir>//' | sed 's/<\\/basedir>//'`;
	if [ ! -d $LAST_DRIVER_DIR ]; then
		ldv_print "ERROR: Can't find driver dir from csd xml.";
		exit 1;
	fi;
	CURRENT_TEMPDIR_NAME=`echo $xml_after_csd | sed 's/^.*'$XML_FILENAME_AFTER_CSD'\([0-9]\+\)\.xml$/\1/'`;
	ldv_print "NORMAL: Process driver number $CURRENT_TEMPDIR_NAME.";
	CURRENT_TEMPDIR=$CSD_DEG_DSCV_TEMPDIR/$CURRENT_TEMPDIR_NAME;
	mkdir $CURRENT_TEMPDIR;
	if [ $? -ne 0 ]; then
	       ldv_print "ERROR: Can't create deg temp directory: \"$CURRENT_TEMPDIR\".";
	       exit 1;
	fi;
	DEG_TEMPDIR=$CURRENT_TEMPDIR/$DEG_TEMPDIR_NAME;
	XML_AFTER_DEG=$DEG_TEMPDIR/$XML_FILENAME_AFTER_DEG;
	DEG_STATE=$DEG_TEMPDIR/$DEG_STATE_FILENAME;
	DEG_STATS=$DEG_TEMPDIR/$STATS_LOG_FILENAME;
	if [ $KERNEL_LEVEL -eq 0 ]; then module_name="--driver-name=$driver"; fi;
#	module_name="--driver-name=$driver";
	ldv_print "NORMAL: Calling Driver Environment Generator";
	ldv_print "DEBUG: LDV_DEBUG=$LDV_DEBUG WORK_DIR=$CURRENT_TEMPDIR $DEG --cmdfile=$xml_after_csd --cmdfile-out=$XML_AFTER_DEG --state-file=$DEG_STATE $koption $module_name;";
	LDV_DEBUG=$LDV_DEBUG WORK_DIR=$CURRENT_TEMPDIR $DEG --basedir=$DEG_TEMPDIR_NAME --cmdfile=$xml_after_csd --cmdfile-out=$XML_AFTER_DEG --state-file=$DEG_STATE $koption $module_name;
	if [ $? -ne 0 ]; then
	        ldv_print "ERROR: Drv-env-gen failed.";
		deg_create_report;
		continue;
	fi;
	if [ ! -f "$XML_AFTER_DEG" ]; then
		ldv_print "ERROR: Cmd file after DEG not exists: \"$XML_AFTER_DEG\".";
		deg_create_report;
		continue;
	fi;
	DSCV_TEMPDIR=$CURRENT_TEMPDIR/$DSCV_TEMPDIR_NAME;
	mkdir $DSCV_TEMPDIR;
	if [ $? -ne 0 ]; then
		ldv_print "ERROR: Can't create DSCV tempdir: \"$DSCV_TEMPDIR\".";
		deg_create_report;
		continue;
	fi;
	DSCV_REPORT=$DSCV_TEMPDIR/$DSCV_REPORT_FILENAME;
	ldv_print "NORMAL: Calling Domain Speicific C-Verifier";
	ldv_print "DEBUG: LDV_RULE_DB=$LDV_RULE_DB WORK_DIR=$DSCV_TEMPDIR $DSCV --cmdfile=$XML_AFTER_DEG --rule-models=$rulemodels --report-out=$DSCV_REPORT";
	LDV_RULE_DB=$LDV_RULE_DB WORK_DIR=$DSCV_TEMPDIR $DSCV --cmdfile=$XML_AFTER_DEG --rule-models=$rulemodels --report-out=$DSCV_REPORT;
	if [ $? -ne 0 ]; then 
		ldv_print "ERROR: DSCV failed."; 
		exit 1;
	fi; 
	deg_create_report;

	ldv_print "NORMAL: Driver number $CURRENT_TEMPDIR_NAME successfully verified.";
done;

#
# add build command stream divider reports
#
CSD_REPORT=$CSD_TEMPDIR/$CSD_REPORT_FILENAME;
ldv_print "NORMAL: Calling Command Stream Divider reporter.";
ldv_print "DEBUG: $CSD_REPORTER --cmdfile=$XML_AFTER_BCE --report-name=$DEG_REPORT_FILENAME --report-out=$CSD_REPORT --state-file=$CSD_STATE --reports-dir=$CSD_DEG_DSCV_TEMPDIR;";
$CSD_REPORTER --cmdfile=$XML_AFTER_BCE --report-name=$DEG_REPORT_FILENAME --report-out=$CSD_REPORT --state-file=$CSD_STATE --reports-dir=$CSD_DEG_DSCV_TEMPDIR;
if [ $? -ne 0 ]; then
        ldv_print "ERROR: CSD reporter failed.";
        exit 1;
fi;

bce_ldv_report;
exit;


