S-tty_insert_flip_string_fixed_flag-test-objs := main.o S-tty_insert_flip_string_fixed_flag.o
U-tty_insert_flip_string_fixed_flag-test-objs := main.o U-tty_insert_flip_string_fixed_flag.o

obj-m += S-tty_insert_flip_string_fixed_flag-test.o
obj-m += U-tty_insert_flip_string_fixed_flag-test.o
