S-tty_wait_until_sent-test-objs := main.o S-tty_wait_until_sent.o
U-tty_wait_until_sent-test-objs := main.o U-tty_wait_until_sent.o

obj-m += S-tty_wait_until_sent-test.o
obj-m += U-tty_wait_until_sent-test.o
