#!/bin/bash

#Script to run LDV-MANAGER.  Uses make you supplied within $MAKE variable

echo "Test presence of control group for LDV Tools"
res-manager -d ldv -o ldv_cgroup_test echo "Control group for LDV Tools was set up properly"
if [ $? != 0 ]; then
{
  echo "You need to set up control group for LDV Tools before using (see \$LDV_TOOLS_SRC/INSTALL for details)"
  cat ldv_cgroup_test
  exit 1
} fi

make_prog=${MAKE:-make}

export LDV_SRVHOME=`readlink -f \`dirname $0\`/../`
ldvm="$LDV_SRVHOME/ldv-manager"

# Where to find stuff
mkscript=$ldvm/mk/ldv-manager.mk

$make_prog -f "$mkscript" "$@"

