#!/bin/bash

#Script to run LDV-MANAGER.  Uses make you supplied within $MAKE variable

echo "Install LDV control group"
install-ldv-cgroup-wrapper
rc=$?
if [[ $rc != 0 ]] ; then
	exit $rc
fi

make_prog=${MAKE:-make}

export LDV_SRVHOME=`readlink -f \`dirname $0\`/../`
ldvm="$LDV_SRVHOME/ldv-manager"

# Where to find stuff
mkscript=$ldvm/mk/ldv-manager.mk

$make_prog -f "$mkscript" "$@"

