#!/bin/bash

#Script to run LDV-MANAGER.  Uses make you supplied within $MAKE variable

make_prog=${MAKE:-make}

export LDV_SRVHOME=`readlink -f \`dirname $0\`/../`
ldvm="$LDV_SRVHOME/ldv-manager"

# Where to find stuff
mkscript=$ldvm/mk/ldv-manager.mk

$make_prog -f "$mkscript" "$@"

