#!/usr/bin/env ruby
#
# Recalculate Problems in the database, given new scripts

require 'rubygems'
require 'active_record'
require 'find'

ENV['LDV_SRVHOME'] ||= File.expand_path("../",File.dirname(__FILE__))
manhome = File.join(ENV['LDV_SRVHOME'],"ldv-manager")

$:.unshift File.join(ENV['LDV_SRVHOME'],'shared','ruby','lib')
require File.join(manhome,"upload_utils.rb")

sql = ldv_db_connect

# We should connect before we load our data model
require File.join(manhome,"results_model.rb")

# By default (and this is the only option), we just recalculate everything
$stderr.write "ldv-problem-recalc: WARNING! ARGUMENTS ARE DEPRECATED AND NOT USED!\n" unless ARGV.empty?
Problem.clear_all(sql)
puts "ldv-problem-recalc: All problems are deleted from database, and will now be recalculated..."

# All tools, all standard scripts
Trace.all.each do |trace|
	Trace.tools.each do |tool,v|
		if tool_stat = trace.send(tool)
			tool_stat.calc_problems(File.join(manhome, "problems", tool))
		end
	end
end

