#!/usr/bin/perl

# Fix reports by adding tag and driver information to them
sub usage
{ die<<EOF
Usage:
	report-fixup report.xml git_tag driver_name driver_origin sources_dir
EOF
}

my ($report_xml,$git_tag,$driver_name,$driver_origin,$sources_dir) = @ARGV;
$driver_origin or usage();

use strict;
use XML::Twig;

sub handle_report
{
	my ($twig, $cmdT) = @_;
	my $launchT = XML::Twig::Elt->new('launch_info');
	my $verifier = undef;
	# Add more verifiers here if you want to override them
	$verifier ||= $ENV{'RCV_VERIFIER'};
	XML::Twig::Elt->new('globalverifier',{},$verifier)->paste($launchT) if defined $verifier;
	XML::Twig::Elt->new('timestamp',{},`date`)->paste($launchT);
	XML::Twig::Elt->new('driver',{},$driver_name)->paste($launchT);
	XML::Twig::Elt->new('driver_origin',{},$driver_origin)->paste($launchT);
	XML::Twig::Elt->new('tag',{},$git_tag)->paste($launchT);
	XML::Twig::Elt->new('sources',{},$sources_dir)->paste($launchT) if defined $sources_dir && -d $sources_dir;
	$launchT->paste($cmdT);
	$cmdT->print('indented');
}

XML::Twig->new( twig_roots => { reports => \&handle_report }, twig_print_outside_roots => \*STDOUT )->parsefile($report_xml);


