S-tty_chars_in_buffer-test-objs := main.o S-tty_chars_in_buffer.o
U-tty_chars_in_buffer-test-objs := main.o U-tty_chars_in_buffer.o

obj-m += S-tty_chars_in_buffer-test.o
obj-m += U-tty_chars_in_buffer-test.o
