S-tty_insert_flip_char-test-objs := main.o S-tty_insert_flip_char.o
U-tty_insert_flip_char-test-objs := main.o U-tty_insert_flip_char.o

obj-m += S-tty_insert_flip_char-test.o
obj-m += U-tty_insert_flip_char-test.o
