U-spin_lock-vmalloc_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-vmalloc_nonatomic-spin_unlock.o
U-spin_lock-vmalloc_32_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-vmalloc_32_nonatomic-spin_unlock.o
U-spin_lock-vmalloc_32_user_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-vmalloc_32_user_nonatomic-spin_unlock.o
U-spin_lock-vmalloc_exec_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-vmalloc_exec_nonatomic-spin_unlock.o
U-spin_lock-vmalloc_node_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-vmalloc_node_nonatomic-spin_unlock.o
U-spin_lock-vmalloc_user_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-vmalloc_user_nonatomic-spin_unlock.o
U-spin_lock-vzalloc_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-vzalloc_nonatomic-spin_unlock.o
U-spin_lock-vzalloc_node_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-vzalloc_node_nonatomic-spin_unlock.o

obj-m += U-spin_lock-vmalloc_nonatomic-spin_unlock-test.o
obj-m += U-spin_lock-vmalloc_32_nonatomic-spin_unlock-test.o
obj-m += U-spin_lock-vmalloc_32_user_nonatomic-spin_unlock-test.o
obj-m += U-spin_lock-vmalloc_exec_nonatomic-spin_unlock-test.o
obj-m += U-spin_lock-vmalloc_node_nonatomic-spin_unlock-test.o
obj-m += U-spin_lock-vmalloc_user_nonatomic-spin_unlock-test.o
obj-m += U-spin_lock-vzalloc_nonatomic-spin_unlock-test.o
obj-m += U-spin_lock-vzalloc_node_nonatomic-spin_unlock-test.o
