<?php

include 'general.php';

// Print error if so and finish execution.
if (isset($this->error)) {
  echo $this->error;
  return;
}

// Get all infomation to be displayed.
$results = $this->entries;

print_r($results['Error trace']->errorTrace);

// Print show/hide plugin for error trace visualizer log. By default it isn't shown.
echo "<script type='text/javascript'>
        $(document).ready(function() {
          $('#SETVLogShowHideLink').toggle(function() {
            $('#SETVLog').show();
            return false;
          } , function() {
            $('#SETVLog').hide();
            return false;
          });
        });
      </script>";

echo "<div id='SETVLogShowHide'><a href='#' id='SETVLogShowHideLink'>Error trace visualizer log</a></div>";

echo "<div id='SETVLog' style='display: none;'>";
echo implode('<br>', $results['ETV log']);
echo "</div>";

printInfo($results);

?>
