<?php

include 'general.php';

// Get all infomation to be displayed.
$results = $this->entries;

// Print error if so.
if (isset($this->error)) {
  echo $this->error;
}
else {
  print_r($results['Error trace']->errorTrace);

  // Print KB records relevant to a given error trace.
  $kbRecords = $results['Knowledge base'];

  echo "<script type='text/javascript'>
          $(document).ready(function() {
            $('.SETVKBDeleteKBRecord').click(function() {
              var rowCur = $(this).parent().parent();
              var kbId = rowCur.find('.SETVKBId').text();

              if (!kbId) {
                alert('Can\'t find corresponding KB id for the record to be deleted');
                return false;
              }

              $.ajaxSetup({ 'error': function() {
                alert('Something goes wrong while KB record was deleted');
              }});

              $.getJSON(
                '" . $this->url(array('action' => 'delete-kb-record')) . "'
                , { 'KB id': kbId }
                , function(results) {
                    if (results.errors == '') {
                      rowCur.remove();
                    }
                    else
                      alert($.makeArray(results.errors).join('\\n'));
                  });

              return false;
            });
          });
        </script>";

  echo "<table id='SETVKBTable' border='1'>";
  echo "<tr id='SETVKBTableFirstRow'>";
  // Print auxiliary column that will contain delete action.
  echo '<td></td>';
  foreach (array_keys($kbRecords[0]) as $columnName) {
    echo "<td>$columnName</td>";
  }
  foreach ($kbRecords as $kbRecord) {
    echo '<tr>';
    echo "<td><a href='' class='SETVKBDeleteKBRecord' title='Delete KB record'>x</a></td>";
    foreach ($kbRecord as $columnName => $kbCellValue) {
      echo "<td><div class='SETVKB" . preg_replace('/\s*/', '', $columnName) . "'>$kbCellValue</div></td>";
    }
    echo '</tr>';
  }
  echo '</tr>';
  echo '</table>';
}

// Print show/hide plugin for error trace visualizer help. By default it isn't shown.
echo "<script type='text/javascript'>
        $(document).ready(function() {
          $('.ETVHelp').before('<div id=\"SETVHelpShowHide\"><a href=\"#\" id=\"SETVHelpShowHideLink\">Error trace visualizer help</a></div>');
          $('#SETVHelpShowHideLink').toggle(function() {
            $('.ETVHelp').show();
            return false;
          } , function() {
            $('.ETVHelp').hide();
            return false;
          });
        });
      </script>";

// Print show/hide plugin for error trace visualizer log. By default it isn't shown.
echo "<script type='text/javascript'>
        $(document).ready(function() {
          $('#SETVLogShowHideLink').toggle(function() {
            $('#SETVLog').show();
            return false;
          } , function() {
            $('#SETVLog').hide();
            return false;
          });
        });
      </script>";

echo "<div id='SETVLogShowHide'><a href='#' id='SETVLogShowHideLink'>Error trace visualizer log</a></div>";

echo "<div id='SETVLog' style='display: none;'>";
echo implode('<br />', $results['ETV log']);
echo "</div>";

printInfo($results);

?>
