DROP TABLE IF EXISTS TASKS;
DROP TABLE IF EXISTS SPLITTED_TASKS;
DROP TABLE IF EXISTS CLIENTS;

CREATE CACHED TABLE IF NOT EXISTS CLIENTS(
	id INT PRIMARY KEY AUTO_INCREMENT, 
	name VARCHAR(255) NOT NULL, 
	status VARCHAR(255) NOT NULL);

CREATE CACHED TABLE IF NOT EXISTS TASKS(
	id INT PRIMARY KEY AUTO_INCREMENT, 
	status VARCHAR(255) NOT NULL, 
	size INT, 
	data BLOB);

CREATE CACHED TABLE IF NOT EXISTS SPLITTED_TASKS(
	id INT PRIMARY KEY AUTO_INCREMENT, 
	parent_id INT NOT NULL, 
	env VARCHAR(100), rule CHAR(5), 
	status VARCHAR(255) NOT NULL, 
	client_id INT NOT NULL);
