#!/usr/bin/env ruby
# Application for LDV Cluster queue management
# Handles what nodes are available for different types of tasks, and performs the work.


require 'rubygems'
require 'nanite'
require 'options.rb'

opts_p = ClusterOptionsParser.new({})
opts_p.do_parse

EM.run do
	start_queue
end



