#!/bin/bash

LDV_HOME=`readlink -f \`dirname $0\`/../`;
CLUSTER_HOME=$LDV_HOME/cluster
export GEM_PATH=$CLUSTER_HOME/ruby:$LDV_HOME/shared/ruby/gem:`gem env gempath`
export PATH=$CLUSTER_HOME:$CLUSTER_HOME/ruby-bin:$PATH
export RUBYLIB=$LDV_HOME/shared/ruby/lib:$RUBYLIB

ldvc-mapper --nanite $CLUSTER_HOME "$@" &
# If initialization failed, give mapper some time to spit an error
sleep 1
ldvc-queue --nanite $CLUSTER_HOME "$@" &

wait %1 %2

