#!/usr/bin/env ruby
# Application for LDV Cluster queue management
# Handles what nodes are available for different types of tasks, and performs the work.


require 'rubygems'
require 'nanite'
$:.unshift File.dirname(__FILE__)
require 'waiter.rb'
require 'options.rb'

opts_p = ClusterOptionsParser.new({})
opts_p.do_parse

EM.run do
	agent = Nanite::Agent.new( {:host => 'localhost', :user => 'mapper', :vhost => '/nanite', :log_level => 'debug', :format => :json, :ping_time => 4, :identity => 'main_queue', :services => ['/ldvqueue/announce']}.merge opts_p.options)
	agent.run
	agent.registry.actors['ldvqueue'].init_waiter({:host => 'localhost', :user => 'mapper', :vhost => '/nanite', :format => :json}.merge opts_p.options)

end



