#!/bin/bash

LDV_HOME=`readlink -f \`dirname $0\`/../`;
CLUSTER_HOME=$LDV_HOME/cluster
export GEM_PATH=$CLUSTER_HOME/ruby:$LDV_HOME/shared/ruby/gem:`gem env gempath`
export PATH=$CLUSTER_HOME:$CLUSTER_HOME/ruby-bin:$PATH

# Threadpool is necessary for spawning child processes.  Keep that number as at least "the number of children you're going to run plus one"
ldvc-node-impl --nanite $CLUSTER_HOME --initrb $CLUSTER_HOME/node.rb --threadpool 20 --format json "$@"

#nanite-agent --nanite $CLUSTER_HOME --initrb $CLUSTER_HOME/node.rb --format json "$@"


