#!/usr/bin/perl
# Small wrapper to just run test sets rather than track regressions.

printf "Auto-removing trash from previous launch:
rm -rf launcher-working-dir/ launcher-results-dir/ regr-task-new regr-test.diff";
system("rm -rf launcher-working-dir/ launcher-results-dir/ regr-task-new regr-test.diff") and die;

$ENV{'LDVDBHOSTTEST'}=$ENV{'LDVDBHOST'} || 'localhost';
$ENV{'LDVDBTEST'}=$ENV{'LDVDB'};
$ENV{'LDVUSERTEST'}=$ENV{'LDVUSER'};
$ENV{'LDVPASSWDTEST'}=$ENV{'LDVPASSWD'};

my $curr_dt = `date +%F-%H-%M-%S`; chomp $curr_dt;
$ENV{'LDV_TASK_NAME'} ||= $curr_dt;

$"=' ';
printf "Launch regression tests:
regr-test.pl --no-check --test-set @ARGV\n";

$ENV{'LDV_DEBUG'} ||= '20';
my $call = join (" ", map {"'$_'"} @ARGV);

system("regr-test.pl --no-check --test-set $call 2>&1 | tee -a test_logs") and die;

