S-tty_port_close_start-test-objs := main.o S-tty_port_close_start.o
U-tty_port_close_start-test-objs := main.o U-tty_port_close_start.o

obj-m += S-tty_port_close_start-test.o
obj-m += U-tty_port_close_start-test.o
