S-empty-test-objs := main.o S-empty.o
S-kfree_skb-test-objs := main.o S-kfree_skb.o
S-kfree_skb1-kfree_skb2-test-objs := main.o S-kfree_skb1-kfree_skb2.o
U-kfree_skb1-kfree_skb1-test-objs := main.o U-kfree_skb1-kfree_skb1.o
U-kfree_skb1-kfree_skb2-kfree_skb1-test-objs := main.o U-kfree_skb1-kfree_skb2-kfree_skb1.o

obj-m += S-empty-test.o
obj-m += S-kfree_skb-test.o
obj-m += S-kfree_skb1-kfree_skb2-test.o
obj-m += U-kfree_skb1-kfree_skb1-test.o
obj-m += U-kfree_skb1-kfree_skb2-kfree_skb1-test.o

