U-spin_lock-kzalloc_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-kzalloc_nonatomic-spin_unlock.o
S-spin_lock-kzalloc_atomic-spin_unlock-test-objs := main.o S-spin_lock-kzalloc_atomic-spin_unlock.o

obj-m += U-spin_lock-kzalloc_nonatomic-spin_unlock-test.o
obj-m += S-spin_lock-kzalloc_atomic-spin_unlock-test.o
