#!/usr/bin/perl
# Problem finder for BLAST tool

$\ = "\n";
$, = "\n";
while (<>){
	chomp;
	/\bexception\b/i and print "Exception";
	/combining structure and non-structure values/i and print "BLAST_combinig";
	/Attempt to access a non structure value as a structure/i and print "BLAST_LLVM_nonstruct";
	/Memory Limit Exceeded/i and print "Out_of_memory";
	/Time Limit Exceeded/i and print "Time_limit";
	/C_System_Descr.initialize: duplicate function name/i and print "Dupl_function", "BLAST_frontend";
	/Recursive Call Graph/i and print "Recursion";
	/Simplify raised exception End_of_file/i and print "Solver";
	/Unary operation on pointer not supported/i and print "BLAST_Unsupported", "BLAST_frontend";
	/frontc reported an error/i and print "BLAST_Compile", "BLAST_frontend";
	/AlignOfE not handled/i and print "BLAST_Unsupported", "BLAST_frontend";
	/convertCilExp: align not handled/i and print "BLAST_Unsupported", "BLAST_frontend";
	/SMT sovler answer is strange: \*\*\* Parse Error: .*: syntax error/i and print "CVC3 Solver parse error";
	/Errormsg\.Error/i and print "Parsing errors";
	/simplemem: temporary needed outside a function/i and print "Temp outside func"; 
	/Invalid_argument\("Predicate index is less than zero"\)/ and print "Large_int";
	/FociInterface.SAT/ and print "Blocks_SAT";
}

