#!/usr/bin/perl
# Problem finder for BLAST tool

$\ = "\n";
$, = "\n";
while (<>){
	chomp;
	/\bexception\b/i and print "Exception";
	/combining structure and non-structure values/i and print "BLAST_combinig";
	/Attempt to access a non structure value as a structure/i and print "BLAST_LLVM_nonstruct";
	/Memory Limit Exceeded/i and print "Out_of_memory";
	/Time Limit Exceeded/i and print "Time_limit";
	/Hangup Detected/i and print "Hangup_detected";
	/C_System_Descr.initialize: duplicate function name/i and print "Dupl_function", "BLAST_frontend";
	/Recursive Call Graph/i and print "Recursion";
	/Simplify raised exception End_of_file/i and print "Solver";
	/Unary operation on pointer not supported/i and print "BLAST_Unsupported", "BLAST_frontend";
	/frontc reported an error/i and print "BLAST_Compile", "BLAST_frontend";
	/AlignOfE not handled/i and print "BLAST_Unsupported", "BLAST_frontend";
	/convertCilExp: align not handled/i and print "BLAST_Unsupported", "BLAST_frontend";
	/SMT sovler answer is strange: \*\*\* Parse Error: .*: syntax error/i and print "CVC3 Solver parse error";
	/Errormsg\.Error/i and print "Parsing errors";
	/simplemem: temporary needed outside a function/i and print "Temp outside func"; 
	/Invalid_argument\("Predicate index is less than zero"\)/ and print "Large_int";
        /SymbolicStore\.Value\.Invalid_access\("Attempt to use Null pointer as a base of offset address"\)/ and print "SymStore_Null";
        /Failure\("hd"\)/ and print "Failure_hd";
	/FociInterface.SAT/ and print "Blocks_SAT";
	/NoNewPredicatesException/ and print "NoNewPredicates";
	/Fatal error: out of memory./ and print "Ocaml_OOM";
        /Error: Global __constr_expr_[0-9]* was already defined at/i and print "ConstExpr";
	/Global .* was already defined/ and print "Two_globals";
	/error when reading CSIsat output/ and print "CSIsat";
}

