#!/usr/bin/perl
# Problem finder for BLAST tool

$\ = "\n";
$, = "\n";
while (<>){
	chomp;
	/Syntax error in line / and print "Syntax_error";
	/Expression is not free of side-effects/ and print "Side";
	/Invalid configuration: Function ldv_main(.*) not found!/ and print "Main not found";
	/unknown initializer: CASTDesignatedInitializer/ and print "CASTDesignatedInitializer";
	/Unknown unary operator/ and print "Unary";
	/Duplicate label (.*) in function/ and print "Duplicate label";
	/File (.*) does not exist!/ and print "File not exists";
	/AbstractGNUSourceCodeParser.parseCompoundStatement/ and print "Compound statement";
	/CPAchecker.run, SEVERE/ and print "SEVERE";
	/java.lang.OutOfMemoryError: (.*)/ and print "Java OutOfmemory";
	/java.lang.AssertionError/ and print "Assertion";
	#/org.sosy_lab.cpachecker.util.predicates.CtoFormulaConverter.buildLvalueTerm/ and print "CtoFormulaConverter"; collision with Out of memory
	/java.lang.AssertionError: org.sosy_lab.cpachecker.cfa.ast.IASTBinaryExpression/ and print "IASTBinaryExpression";
	/org.sosy_lab.cpachecker.util.predicates.mathsat.MathsatInterpolatingProver.getInterpolant/ and print "MathsatInterpolatingProver";
	/No new predicates/ and print "NoNewPredicates"; #org.sosy_lab.cpachecker.exceptions.RefinementFailedException[No new predicates]
	/cpa.sh: line (.*): (.*) Aborted/ and print "Aborted";
}


