#!/usr/bin/perl
# Problem finder for generic RCV issues

$\ = "\n";
$, = "\n";
while (<>){
	chomp;
	/PREPROCESS/ and print "CPP_error";
	/CIL ERROR/ and print "CIL_parse_error";
	/No entry point or error location found/ and print "Main/Label";
	/time exhausted/ and print "Time exhausted";
	/memory exhausted/ and print "Memory exhausted";
	/killed by signal/ and print "Signal";

	# See shared/perl/modules/DSCV/RCV/Library.pm
	/VERIFIER SCRIPT ERROR/ and print "Script";
}


