S-tty_port_block_til_ready-test-objs := main.o S-tty_port_block_til_ready.o
U-tty_port_block_til_ready-test-objs := main.o U-tty_port_block_til_ready.o

obj-m += S-tty_port_block_til_ready-test.o
obj-m += U-tty_port_block_til_ready-test.o
