S-dec-lock-test-objs := main.o S-dec-lock.o
U-dec-double-test-objs := main.o U-dec-double.o
U-dec-lock-test-objs := main.o U-dec-lock.o
U-dec-wrong-test-objs := main.o U-dec-wrong.o

obj-m += S-dec-lock-test.o
obj-m += U-dec-double-test.o
obj-m += U-dec-lock-test.o
obj-m += U-dec-wrong-test.o

