S-tty_port_close_end-test-objs := main.o S-tty_port_close_end.o
U-tty_port_close_end-test-objs := main.o U-tty_port_close_end.o

obj-m += S-tty_port_close_end-test.o
obj-m += U-tty_port_close_end-test.o
