obj-m += U-no_mutex_unlock_after_atomic_dec_and_mutex_lock.o
obj-m += U-no_mutex_unlock_after_mutex_lock.o
obj-m += U-no_mutex_unlock_after_mutex_lock_interruptible.o
obj-m += U-no_mutex_unlock_after_mutex_lock_killable.o
obj-m += U-no_mutex_unlock_after_mutex_trylock.o

