<?php echo $this->doctype(), "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Linux driver verification statistics</title>
  <?php
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/global.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/etv.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/etv-stats.css');
    $this->headScript()->appendFile($this->baseUrl() . '/jslib/jquery-1.4.2.min.js', 'text/javascript');
    echo $this->headLink();
    echo $this->headScript();
  ?>
</head>
<body>
<div id="SSHeader">
  <div id="SSHeaderLogo">Linux driver verification statistics</div>
<!-- There is no action implemented at the moment.
  <div id="SSHeaderNavigation" style="float: right">
    <a href="<?php /*echo $this->url(
      array('controller'=>'index'),
      'default',
      true)*/ ?>">Choose profile</a>
  </div>
-->
</div>

<?php echo $this->layout()->content ?>

</body>
</html>
