<?php
/*
 * Copyright (C) 2010-2012
 * Institute for System Programming, Russian Academy of Sciences (ISPRAS).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
function toolNameVersion()
{
  $version = '0.02';
  return "LDV Analytics Center $version";
}

echo $this->doctype(), "\n"
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php echo toolNameVersion() ?></title>
  <?php
    $baseUrl = $this->baseUrl();
    $this->headLink()->appendStylesheet("$baseUrl/css/global.css");
    $this->headLink()->appendStylesheet("$baseUrl/css/etv.css");
    $this->headLink()->appendStylesheet("$baseUrl/css/etv-analytics-center.css");
    $this->headScript()->appendFile("$baseUrl/jslib/jquery-1.4.2.min.js", 'text/javascript');
    $this->headScript()->appendFile("$baseUrl/jslib/jquery.jeditable.mini.js", 'text/javascript');
    $this->headScript()->appendFile("$baseUrl/jslib/etv.js", 'text/javascript');
    echo $this->headLink();
    echo $this->headScript();
  ?>
</head>
<body>
<div id="SSHeader">
  <div id="SSHeaderLogo"><?php echo toolNameVersion() ?></div>
  <div id="SSHeaderMenu" >
    <!--<a href="<?php echo $this->url(array('controller'=>'stats', 'action'=>'index'), 'default', true) ?>">Show statistics</a> &nbsp &nbsp-->
    <!--<a href="<?php echo $this->url(array('controller'=>'stats', 'action'=>'signdb'), 'default', true) ?>">Sign database connection</a> &nbsp &nbsp-->
    <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'), 'default', true) ?>">Help</a> &nbsp &nbsp
    <a href="mailto:joker@ispras.ru?subject=Questions about <?php echo toolNameVersion() ?>">Support</a>
  </div>
</div>

<?php echo $this->layout()->content ?>

</body>
</html>
