<?php 
/*
 * Copyright (C) 2010-2012
 * Institute for System Programming, Russian Academy of Sciences (ISPRAS).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

echo $this->doctype(), "\n"
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Linux driver verification statistics</title>
  <?php
    $baseUrl = $this->baseUrl();
    $this->headLink()->appendStylesheet("$baseUrl/css/global.css");
    $this->headLink()->appendStylesheet("$baseUrl/css/etv.css");
    $this->headLink()->appendStylesheet("$baseUrl/css/etv-analytics-center.css");
    $this->headScript()->appendFile("$baseUrl/jslib/jquery-1.4.2.min.js", 'text/javascript');
    $this->headScript()->appendFile("$baseUrl/jslib/jquery.jeditable.mini.js", 'text/javascript');
    $this->headScript()->appendFile("$baseUrl/jslib/etv.js", 'text/javascript');
    echo $this->headLink();
    echo $this->headScript();
  ?>
</head>
<body>
<div id="SSHeader">
  <div id="SSHeaderLogo">Linux driver verification statistics</div>
<!-- There is no action implemented at the moment.
  <div id="SSHeaderNavigation" style="float: right">
    <a href="<?php /*echo $this->url(
      array('controller'=>'index'),
      'default',
      true)*/ ?>">Choose profile</a>
  </div>
-->
</div>

<?php echo $this->layout()->content ?>

</body>
</html>
