S-multiple-ioremap-test-objs := S-multiple-ioremap.o
S-single-ioremap-test-objs := S-single-ioremap.o
S-single-ioremap-cache-test-objs := S-single-ioremap-cache.o
U-multiple-ioremap-test-objs := U-multiple-ioremap.o
U-multiple-unmap-test-objs := U-multiple-unmap.o
U-no-unmap-test-objs := U-no-unmap.o
U-only-unmap-test-objs := U-only-unmap.o

obj-m += S-multiple-ioremap-test.o
obj-m += S-single-ioremap-test.o
obj-m += S-single-ioremap-cache-test.o
obj-m += U-multiple-ioremap-test.o
obj-m += U-multiple-unmap-test.o
obj-m += U-no-unmap-test.o
obj-m += U-only-unmap-test.o
