<?php
/*
 * Copyright (C) 2010-2012
 * Institute for System Programming, Russian Academy of Sciences (ISPRAS).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//TODO move this to set up action.
//$this->form->setAction($this->url());
//echo $this->form;
?>

<!--TODO <h2>User guide</h2>-->
<h2>Feel free to ask questions and make feedback</h2>
<p>Follow link 'Support' at the page right-up corner</p>

<br><br>

<h2>LDV Analytics Cenver change log</h2>
<h3><a name="0.02">0.02</a></h3>
<ul>
  <li>Move note about time, forms for comparison and CSV printing after the main statistics table.</li>
</ul>
<h3><a name="0.01">0.01</a></h3>
<ul>
  <li>Initial release.</li>
</ul>
