<?php
/*
 * Copyright (C) 2010-2012
 * Institute for System Programming, Russian Academy of Sciences (ISPRAS).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//TODO move this to set up action.
//$this->form->setAction($this->url());
//echo $this->form;
?>

<!--TODO <h2>User guide</h2>-->
<h2>Feel free to ask questions and make feedback</h2>
<p>Follow link 'Support' at the page right-up corner</p>

<br><br>

<h2>LDV Analytics Cenver change log</h2>
<h3><a name="0.11">0.11</a></h3>
<ul>
  <li>Add ability to authorise on <i>linuxtesting.org</i> to perform any action regarding Knowledge Base (if LDV Analytics Center is installed with environment variable LDV_AUTHORIZATION).</li>
  <li>Error traces can be published with associated Knowledge Bace record to the Public Pool of Bugs on <i>linuxtesting.org</i>.</li>
  <li>Add a new interface to LDV Knowledge Base that is aimed to show unsafes or/and (associated) Knowledge Base records with various filters.</li>
</ul>
<h3><a name="0.10">0.10</a></h3>
<ul>
  <li>Better usage of the window height by error trace visualization (<a href="http://forge.ispras.ru/issues/4581">#4581</a>).</li>
</ul>
<h3><a name="0.09">0.09</a></h3>
<ul>
  <li>Integrate with standalone Error Trace Visualization.</li>
</ul>
<h3><a name="0.08">0.08</a></h3>
<ul>
  <li>Add page size to Auxiliary information section.</li>
</ul>
<h3><a name="0.07">0.07</a></h3>
<ul>
  <li>Fix bad layout of tabs in error trace visualizer (<a href="http://forge.ispras.ru/issues/4431">#4431</a>).</li>
  <li>Use more ergonomic ratio between widths of error trace and source code text fields. Keep this ratio during resizing.</li>
</ul>
<h3><a name="0.06">0.06</a></h3>
<ul>
  <li>Better usage of the window width by error trace visualization (<a href="http://forge.ispras.ru/issues/4417">#4417</a>).</li>
</ul>
<h3><a name="0.05">0.05</a></h3>
<ul>
  <li>Compares call stacks instead of call trees by default (<a href="http://forge.ispras.ru/issues/3829">#3829</a>).</li>
</ul>
<h3><a name="0.04">0.04</a></h3>
<ul>
  <li>Fix problems with conversions to and from 'deleted' in comparison (<a href="http://forge.ispras.ru/issues/3355">#3355</a>).</li>
  <li>Temporarily turn off partial showing of additional information for unsafes in comparison (<a href="http://forge.ispras.ru/issues/1514">#1514</a>).</li>
</ul>
<h3><a name="0.03">0.03</a></h3>
<ul>
  <li>Set up password for KB recalculator if so (<a href="http://forge.ispras.ru/issues/1722">#1722</a>).</li>
</ul>
<h3><a name="0.02">0.02</a></h3>
<ul>
  <li>Move note about time, forms for comparison and CSV printing after the main statistics table.</li>
</ul>
<h3><a name="0.01">0.01</a></h3>
<ul>
  <li>Initial release.</li>
</ul>
