S-usb_gadget_register_driver-test-objs := S-usb_gadget_register_driver.o
S-register_chrdev_region--X33X-unregister_chrdev_region-test-objs := S-register_chrdev_region--X33X-unregister_chrdev_region.o
S-register_chrdev_region--X107X-unregister_chrdev_region-test-objs := S-register_chrdev_region--X107X-unregister_chrdev_region.o
S-class_create-register_c-X137X-unregister_chrdev_region-test-objs := S-class_create-register_c-X137X-unregister_chrdev_region.o
S-class_register-usb_gadg-X212X-ter_driver-class_destroy-test-objs := S-class_register-usb_gadg-X212X-ter_driver-class_destroy.o

obj-m += S-usb_gadget_register_driver-test.o
obj-m += S-register_chrdev_region--X33X-unregister_chrdev_region-test.o
obj-m += S-register_chrdev_region--X107X-unregister_chrdev_region-test.o
obj-m += S-class_create-register_c-X137X-unregister_chrdev_region-test.o
obj-m += S-class_register-usb_gadg-X212X-ter_driver-class_destroy-test.o
