S-empty-test-objs := main.o S-empty.o
S-usb_register-PROPAGATED-test-objs := main.o S-usb_register-PROPAGATED.o
S-register_netdev-PROPAGATED-test-objs := main.o S-register_netdev-PROPAGATED.o
U-usb_register-UNCHECKED-test-objs := main.o U-usb_register-UNCHECKED.o
U-register_netdev-UNCHECKED-test-objs := main.o U-register_netdev-UNCHECKED.o

obj-m += S-empty-test.o
obj-m += S-usb_register-PROPAGATED-test.o
obj-m += S-register_netdev-PROPAGATED-test.o
obj-m += U-usb_register-UNCHECKED-test.o
obj-m += U-register_netdev-UNCHECKED-test.o
