U-spin_lock-usb_submit_urb_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-usb_submit_urb_nonatomic-spin_unlock.o
S-spin_lock-usb_submit_urb_atomic-spin_unlock-test-objs := main.o S-spin_lock-usb_submit_urb_atomic-spin_unlock.o
U-spin_lock-usb_alloc_urb_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-usb_alloc_urb_nonatomic-spin_unlock.o
S-spin_lock-usb_alloc_urb_atomic-spin_unlock-test-objs := main.o S-spin_lock-usb_alloc_urb_atomic-spin_unlock.o
U-spin_lock-usb_alloc_coherent_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-usb_alloc_coherent_nonatomic-spin_unlock.o
S-spin_lock-usb_alloc_coherent_atomic-spin_unlock-test-objs := main.o S-spin_lock-usb_alloc_coherent_atomic-spin_unlock.o

obj-m += U-spin_lock-usb_submit_urb_nonatomic-spin_unlock-test.o
obj-m += S-spin_lock-usb_submit_urb_atomic-spin_unlock-test.o
obj-m += U-spin_lock-usb_alloc_urb_nonatomic-spin_unlock-test.o
obj-m += S-spin_lock-usb_alloc_urb_atomic-spin_unlock-test.o
obj-m += U-spin_lock-usb_alloc_coherent_nonatomic-spin_unlock-test.o
obj-m += S-spin_lock-usb_alloc_coherent_atomic-spin_unlock-test.o
