S-tty_driver_flush_buffer-test-objs := main.o S-tty_driver_flush_buffer.o
U-tty_driver_flush_buffer-test-objs := main.o U-tty_driver_flush_buffer.o

obj-m += S-tty_driver_flush_buffer-test.o
obj-m += U-tty_driver_flush_buffer-test.o
