U-spin_lock-pskb_expand_head_nonatomic-spin_unlock-test-objs := main.o U-spin_lock-pskb_expand_head_nonatomic-spin_unlock.o
S-spin_lock-pskb_expand_head_atomic-spin_unlock-test-objs := main.o S-spin_lock-pskb_expand_head_atomic-spin_unlock.o

obj-m += U-spin_lock-pskb_expand_head_nonatomic-spin_unlock-test.o
obj-m += S-spin_lock-pskb_expand_head_atomic-spin_unlock-test.o
