S-sysfs-single-obj-mult-group-test-objs := S-sysfs-single-obj-mult-group.o
S-sysfs-single-obj-single-group-test-objs := S-sysfs-single-obj-single-group.o
U-sysfs-single-obj-mult-group-test-objs := U-sysfs-single-obj-mult-group.o
U-sysfs-single-obj-single-group-test-objs := U-sysfs-single-obj-single-group.o

obj-m += S-sysfs-single-obj-mult-group-test.o
obj-m += S-sysfs-single-obj-single-group-test.o
obj-m += U-sysfs-single-obj-mult-group-test.o
obj-m += U-sysfs-single-obj-single-group-test.o
